#!/bin/bash

# salve colors
blue='\033[1;36m'
green='\033[1;32m'
no_color='\033[0m' # No Color

# -------------- #

function compile_plugin {
  # go to directory
  cd ${1}

  # create necessary directories
  mkdir build -p

  # compile
  cd build
  cmake ..
  make

  # remove compilation files
  rm -rf *

  # go back to plugins directory
  cd ../..
}

# -------------- #

# check for help
if [[ "${1}" == "--help" ]]  || [[ "${1}" == "-h" ]]; then
  echo -e "script/compile - compile Autobotz Simulator plugins"
  echo -e "SINTAXE: script/compile [Plugins]"
  echo -e "Plugins:"
  echo -e "\t Name of each plugin you want to compile [Sintaxe: UPPERCASEPROJECT_snake_case_name]"
  echo -e "\t all: compile all plugins"

  exit 0
fi

# -------------- #

# go to plugins directory
cd plugins/

# -------------- #

# select plugins to be compiled
if [[ "${1}" == "all" ]] || [[ ! ${1}  ]] ; then
  list="*/"
else
  list="${@}"
fi

# -------------- #

# loop though selected plugins and compile them
for dir in ${list} ; do
  echo -e "${blue}Compiling ${dir} plugin...${no_color}"
  compile_plugin $dir
  echo -e "${green}${dir} plugin is ready${no_color}"
done

exit 0
